// <auto-generated />
using EnityAsss5.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnityAsss5.Migrations
{
    [DbContext(typeof(ComapnySuDatabase))]
    [Migration("20250318101103_intialMigration")]
    partial class intialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFwAsss4.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MangerId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("MangerId")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EntityFwAsss4.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<int>("workDeparmentsId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("workDeparmentsId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EntityFwAsss4.Entities.Department", b =>
                {
                    b.HasOne("EntityFwAsss4.Entities.Employee", "Manger")
                        .WithOne("Department")
                        .HasForeignKey("EntityFwAsss4.Entities.Department", "MangerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manger");
                });

            modelBuilder.Entity("EntityFwAsss4.Entities.Employee", b =>
                {
                    b.HasOne("EntityFwAsss4.Entities.Department", "workDeparments")
                        .WithMany("employees")
                        .HasForeignKey("workDeparmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workDeparments");
                });

            modelBuilder.Entity("EntityFwAsss4.Entities.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("EntityFwAsss4.Entities.Employee", b =>
                {
                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
